name: Lint/Build/Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    uses: dydxprotocol/actions-public/.github/workflows/v3-lint-build-test.yml@main
    secrets: inherit
